version: '3.8'

services:
  training:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "../:/home/testing/model"
    command: /bin/bash /home/testing/model/scripts/exploitdb_script.sh
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

  development:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "../:/home/testing/model"
    stdin_open: true
    tty: true
    command: /bin/bash
    depends_on:
      - training
